/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dummy.kt.jpype

import kotlin.test.Test
import kotlin.test.assertEquals

class TestIterables {
    @Test
    fun testKtIterables() {
        for ((x, y) in (0..10).zip(intRange(0, 10))) {
            assertEquals(x, y)
        }
    }

    @Test
    fun testJvmIterables() {
        for ((x, y) in (0..10).zip(IterablesJava.intRange(0, 10))) {
            assertEquals(x, y)
        }
    }
}
